app = "agentkit-leo"          # change if taken
primary_region = "iad"        # pick closest: iad, lhr, sin, ...

[build]
  dockerfile = "Dockerfile.fly"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    force_https = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
