apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-distribution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-distribution
  template:
    metadata:
      labels:
        app: content-distribution
    spec:
      containers:
      - name: content-distribution
        image: gcr.io/your-project-id/agentkit-content-distribution:latest
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/run/secrets/google/service-account.json
        volumeMounts:
        - name: ayrshare-secret
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: ayrshare-secret
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: ayrshare-spc